### ISSUE TITLE
use rem is not job

### ISSUE THREAD

**Issue by jackzhaojun** [cwdoh/cssparser.js#14]
```css
 .footer {
    position: fixed;
    left: 0;
    bottom: 0;
    overflow: hidden;
    width: 1rem;
}
```
Error: Parse error on line 6:
... hidden;    width: 1rem;}
