### ISSUE TITLE
Parse error when tailing semicolon has been omitted

### ISSUE THREAD

**Issue by cwdoh** [cwdoh/cssparser.js#15]
Twitter css has omitted semicolons on tailing declaration in blocks, and it doesn't be parsed.
> 마지막 세미콜론이 생략된 경우 파싱이 되지 않음.

```css
html {
  font-family: sans-serif;
  -ms-text-size-adjust: 100%;
  -webkit-text-size-adjust:100%
}
```
