### ISSUE TITLE
Asterisk prefixed CSS property name

### ISSUE THREAD

**Issue by cwdoh** [cwdoh/cssparser.js#17]
A hack for IE. [link](http://stackoverflow.com/questions/4563651/what-does-an-asterisk-do-in-a-css-property-name)

```css
.yui-button .first-child
{
    display:block;
    *display:inline-block;
}
```
