### ISSUE TITLE
Computation property value

### ISSUE THREAD

**Issue by cwdoh** [cwdoh/cssparser.js#18]
error case

> border-radius: 3px / 7px

```css
li:before {
  content: "";
  display: block;
  position: absolute;
  width: 3px;
  background-color: #1da1f2;
  left: 35px;
  z-index: 1;
  border-radius: 3px / 7px
}
```
