### ISSUE TITLE
Operation at function parameter

### ISSUE THREAD

**Issue by cwdoh** [cwdoh/cssparser.js#19]
Operation at function parameter.

```css
div.d-Rc-Ya, div.G-q-Ya {
  filter: alpha(opacity=75);
  opacity: .75
}
```
