### ISSUE TITLE
Support IE "hack" properties like _display

### ISSUE THREAD

**Issue by sladiri** [cwdoh/cssparser.js#20]
Would it be possbile to support these? They are IE 7 and below "hacks". I wanted to parse a CSS file from the Tachyons framework, but it fails, because of such prefixed properties. Tachyons uses the undersore character, but I read that asterisk is also used.

example:
```css
.fl { float: left; _display: inline; }
```
