### ISSUE TITLE
Attribute selectors are "undefined"

### ISSUE THREAD

**Issue by sladiri** [cwdoh/cssparser.js#21]
Rules with attribute selectors currently give me wrong output:

```css
button, html [type="button"], [type="reset"], [type="submit"] {
  -webkit-appearance: button;
}
```
results in
```json
{
    "type": "rule",
    "selectors": [
        "button",
        "html [undefined]",
        "[undefined]",
        "[undefined]"
    ],
    "declarations": {
        "-webkit-appearance": "button"
    }
}
```
