### ISSUE TITLE
Option to include comments in json output

### ISSUE THREAD

**Issue by tomgenoni** [cwdoh/cssparser.js#24]
One use case is for documentation. For example, at the top of each CSS file I might include a title and a description. The JSON could then be used to output that information along with the actual CSS.

**Comment by cwdoh** [comment]
Thanks for the request! I agree to your opinion.

I also wanted supporting `comments`, however, I was troubled because there is something difficult to solve. As we know, comments blocks can be located at anywhere in CSS. So, sometimes it's difficult to put comments informations into JSON:

```css
/* field decorator */
.my-field {
    padding-left: 1em; /* left padding */
    /* background color */
    background-color: /* don't fix this */ #fff /* white */
}
```

> I know this is ugly example. but, it's possible. :/
If you have any idea to handle these cases, please let me know. :)
Thanks! :)
